awesomeapp/user/views.py
import imghdr
import os

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user

from awesomeapp.extensions import db
from config import Config
from awesomeapp.user.models import User
from awesomeapp.user.forms import RegistrationForm, LoginForm

blueprint = Blueprint(
    'user',
    __name__,
    url_prefix='/users',
    template_folder='templates'
)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('vizit.start_page'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('user.login'))
        flash('Не верный email или пароль')
        return redirect(url_for('users.login'))
    return render_template('user/login.html', title='Вход', form=form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.visit'))


@blueprint.route('/visit')
def visit():
    src = [
        os.path.join(Config.EQUIPMENT_ICON_PATH, x)
        for x in Config.STOCK_ICON.values()
    ]
    return render_template(
        'user/visit.html',
        title='Привет, спортсмен!',
        src=src)


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('equipment.equipment'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            first_name=form.first_name.data or None,
            second_name=form.second_name.data or None,
            email=form.email.data,
            about_me=form.about_me.data,
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        avatar = form.avatar.data
        if avatar:
            file_type = imghdr.what(avatar)
            filename = f'{user.id}.{file_type}'
            avatar.save(os.path.join(
                Config.GLOBAL_PATH,
                Config.IMAGE_PATH,
                filename))
            user.avatar = os.path.join(Config.IMAGE_PATH, filename)
            db.session.add(user)
            db.session.commit()
        return redirect(url_for('.login'))
    return render_template(
        'user/register.html',
        title='Регистрация',
        form=form
    )

awesomeapp/templates/footer.html
<footer class="text-white mt-2">
    <div class="container-fluid py-2">
        <div class="row">
            <div class="col-md-6 small">Артём @Roxe322, Денис @tlenin_67, Роман @likeulife</div>
            <div class="col-md-3"></div>
            <div class="col-md-3 text-right small align-self-end font-italic">©2019-2020 Awesome team</div>
        </div>
    </div>
</footer>

awesomeapp/templates/index.html
<!doctype html>
<html lang="en">
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/style.css">

    <title>{{ title }}</title>
  </head>
  <body class="text-center">

    {% include('menu.html') %}

    <div class="container">
      <div class="row align-items-center index_content">
        <div class="col-sm-3">

          <div class="user">
            <p>{{ current_user.first_name }} {{ current_user.second_name }}</p>
            <p><img class="index_avatar rounded" src="/{{ current_user.avatar }}" alt="">
            <p class="small_text">О себе:
            <p>{{ current_user.about_me }}
          </div>

          <div class='sport-zone'>
            {% if equipment_by_id %}
              <p>{{ equipment_by_id.name }}</p>
              <img class="index_avatar img-fluid rounded" src="/{{ equipment_by_id.avatar }}" alt="">
              <p class="small_text">Об инвентаре:          
              <p>{{ equipment_by_id.about }}
            {% endif %}
          </div>

        </div>

        <div class="col-sm-9">
          <div class='equipment-carousel'>
            <div class="owl-carousel owl-theme">
              {% for equipment in all_equipment %}
                <a href="{{ url_for('statistics.menu', equipment_id=equipment.id) }}"><img class="equipment_pic" src="/{{ equipment.avatar }}" alt="{{ equipment.id }}"></a>
              {% endfor %}
              <a href="{{ url_for('equipment.equipment') }}"><img class="equipment_plus" src="/static/images/add.svg" alt=""></a>
            </div>
          </div>

          <div class="view-zone">
            {% block content %}
            {% endblock %}
          </div>

        </div>

      </div>
    </div>

    {% include('footer.html') %}
        
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="/static/js/jquery-3.3.1.slim.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/owl.carousel.min.js"></script>
    <script src="/static/js/jquery.maskedinput.min.js"></script>

    <script>
    $(function() {
      $.mask.definitions['5']='[012345]';
      $("#time").mask("99:59:59", {placeholder: "чч:мм:сс" });
      $("#time2").mask("99:59:59", {placeholder: "чч:мм:сс" });
    });
    </script>

    <script>
        $('.owl-carousel').owlCarousel({
          loop:true,
          margin:3,
          responsiveClass:true,
          autoWidth:true,
          responsive:{
              0:{
                  items:1,
                  nav:true
              },
              600:{
                  items:3,
                  nav:false
              },
              1000:{
                  items:5,
                  nav:true,
                  loop:false
              }
          }
      })
    </script>
  </body>
</html>

awesomeapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark ">
  {% if current_user.is_authenticated %}
    <a class="navbar-brand" href="{{ url_for('vizit.start_page')}}">AwesomeStats</a>
  {% else %}
    <a class="navbar-brand" href="{{ url_for('user.visit') }}">AwesomeStats</a>
  {% endif %}

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link">Привет, {{ current_user.email }}!</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.logout') }}">Выход</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">Вход</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>