awesomeapp/statistics/views.py
import imghdr
import os

from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user

from awesomeapp.extensions import db
from config import Config
from awesomeapp.statistics.forms import StatisticsForm, StatisticsMenuForm
from awesomeapp.statistics.models import Stats, Story, Image
from awesomeapp.equipment.models import Equipment
from awesomeapp.statistics.utils import (
    convert_to_meter,
    convert_to_seconds,
    get_statistics_fields,
    delete_images_from_disk,
)


blueprint = Blueprint(
    'statistics',
    __name__,
    template_folder='templates',
    url_prefix='/stats'
)


@blueprint.route('/delete_statistics/<int:statistics_id>/<int:equipment_id>')
def delete_statistics(statistics_id, equipment_id):
    statistics = Stats.get_by_id(statistics_id)
    story = statistics.story

    if story:
        images = story.images
        delete_images_from_disk(images)

    db.session.delete(statistics)
    db.session.commit()
    return redirect(url_for('statistics.menu', equipment_id=equipment_id))


@blueprint.route('/delete_equipment/<int:equipment_id>')
def delete_equipment(equipment_id):
    equipment = Equipment.get_by_id(equipment_id)

    nested_images = [
        statistics.story.images for statistics in equipment.stats
    ]
    flat_images = [
        image for set_images in nested_images for image in set_images
    ]

    if flat_images:
        delete_images_from_disk(flat_images)

    db.session.delete(equipment)
    db.session.commit()
    return redirect(url_for('vizit.start_page'))


@blueprint.route('/menu/<int:equipment_id>', methods=['GET', 'POST'])
@login_required
def menu(equipment_id):
    form = StatisticsMenuForm()
    return render_template(
        'statistics/menu.html',
        form=form,
        title='Меню инвентаря',
        equipment_by_id=Equipment.get_by_id(equipment_id),
        all_equipment=Equipment.get_all(current_user.id)
    )


@blueprint.route('/view/<int:equipment_id>', methods=['GET', 'POST'])
@login_required
def view(equipment_id):
    form = StatisticsMenuForm()
    form.id.data = equipment_id
    print(request)
    if form.validate_on_submit():
        start_date = form.start_date.data
        end_date = form.end_date.data

        if end_date is None:
            end_date = start_date

        return render_template(
            'statistics/stats_view.html',
            start_date=start_date,
            end_date=end_date,
            story_and_images=Stats.get_story_and_images(
                equipment_id, start_date, end_date),
            statistics=Stats.get_statistics(
                equipment_id, start_date, end_date),
            form=form,
            title='Просмотр статистики',
            equipment_by_id=Equipment.get_by_id(equipment_id),
            all_equipment=Equipment.get_all(current_user.id),
            histogram=Stats.histogram_data(start_date, end_date, equipment_id)
        )

    return render_template(
        'statistics/menu.html',
        form=form,
        title='Меню инвентаря',
        equipment_by_id=Equipment.get_by_id(equipment_id),
        all_equipment=Equipment.get_all(current_user.id),
    )


@blueprint.route('/add/<int:equipment_id>', methods=['GET', 'POST'])
@login_required
def add(equipment_id):
    form = StatisticsForm()
    if form.validate_on_submit():
        stats = Stats(
            equipment_id=equipment_id,
            date=form.date.data,
            distance=convert_to_meter(form.distance.data),
            time=convert_to_seconds(form.time.data),
            total_time=convert_to_seconds(form.total_time.data),
            max_speed=convert_to_meter(form.max_speed.data),
            steps=form.steps.data,
            avg_cadence=form.avg_cadence.data,
            max_cadence=form.max_cadence.data,
            avg_heart_rate=form.avg_heart_rate.data,
            max_heart_rate=form.max_heart_rate.data,
            max_temperature=form.max_temperature.data,
            min_temperature=form.min_temperature.data,
            start_altitude=form.start_altitude.data,
            total_up_altitude=form.total_up_altitude.data,
            total_down_altitude=form.total_down_altitude.data,
            min_altitude=form.min_altitude.data,
            max_altitude=form.max_altitude.data,
        )
        db.session.add(stats)
        db.session.commit()

        story_text = form.story.data
        images = form.photo.data
        if (
            story_text == '' and
            images[0].mimetype == 'application/octet-stream'
        ):
            return redirect(url_for('statistics.menu',
                                    equipment_id=equipment_id))

        story = Story(
            text=story_text,
            stats_id=stats.id
        )
        db.session.add(story)
        db.session.commit()

        stats.story_id = story.id
        db.session.add(stats)
        db.session.commit()

        if images[0].mimetype == 'application/octet-stream':
            return redirect(url_for('statistics.menu',
                                    equipment_id=equipment_id))

        for image in images:
            img = Image(story_id=story.id)
            db.session.add(img)
            db.session.commit()
            file_type = imghdr.what(image)
            filename = f'{img.id}.{file_type}'
            image.save(os.path.join(Config.GLOBAL_PATH,
                                    Config.STORY_IMAGE_PATH, filename))
            img.src = os.path.join(Config.STORY_IMAGE_PATH, filename)
            db.session.add(img)
            db.session.commit()

        return redirect(url_for('statistics.menu', equipment_id=equipment_id))

    fields = get_statistics_fields(Equipment.get_by_id(
        equipment_id).type_id, form)

    return render_template(
        'statistics/stats.html',
        title='Ввод данных',
        form=form,
        all_equipment=Equipment.get_all(current_user.id),
        equipment_by_id=Equipment.get_by_id(equipment_id),
        fields=fields
    )

awesomeapp/statistics/templates/statistics/carousel.html
{% if story_and_images.main_image is not none %}
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img 
                    src="/{{ story_and_images.main_image }}" 
                    alt="фотографии тренировки" 
                    class="d-block w-auto img-fluid rounded carousel_image "></p>
            </div>
            {% for image in story_and_images.rest_images %}
                <div class="carousel-item">
                    <img 
                        src="/{{ image }}" 
                        alt="фотографии тренировки" 
                        class="d-block w-auto img-fluid rounded carousel_image"></p>
                </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
{% endif %}

awesomeapp/statistics/templates/statistics/histogram.html
<!-- Load d3.js -->
<script src="/static/js/d3.v3.min.js"></script>
<script src="/static/js/d3.tip.v0.6.3.js"></script>

<script>

    var histogram_div = document.getElementById("my_histogram"); 

    var margin = {top: 40, right: 20, bottom: 90, left: 40},
        width = histogram_div.clientWidth - margin.left - margin.right,
        height = 500 - margin.top - margin.bottom;

    var format = d3.format(".0");

    var data = {{ histogram | tojson }}

    var x = d3.scale.ordinal()
        .rangeRoundBands([0, width], .1);
            
    var y = d3.scale.linear()
        .range([height, 0]);

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom")
        .ticks(2);

    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left")
        .tickFormat(format);

    var tip = d3.tip()
        .attr('class', 'd3-tip')
        .direction('e')
        .offset([0, 20])
        .html(function(d) {
        return "<p>Дата: " + d.Дата + "<p>Дистанция: " + d.Дистанция + "<p>Время: " + d.Время +"<p>Скорость: " + d.Скорость;
    })

    var svg = d3.select("#my_histogram")
        .append("svg")
        .attr("class", "axis")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

          

    svg.call(tip);

    x.domain(data.map(function(d) { return d.Дата; }));
    y.domain([0, d3.max(data, function(d) { return d.Дистанция; })]);

    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis)
        .selectAll("text")
        .attr("y", 0)
        .attr("x", 8)
        .attr("dy", ".35em")
        .attr("transform", "rotate(90)")
        .style("text-anchor", "start");
        

    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)
        .append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .style("text-anchor", "end")
        .text("Дистанция (км)");

    svg.selectAll(".bar")
        .data(data)
        .enter()
        .append("rect")
        .attr("class", "bar")
        .attr("x", function(d) { return x(d.Дата); })
        .attr("width", x.rangeBand())
        .attr("y", function(d) { return y(d.Дистанция); })
        .attr("height", function(d) { return height - y(d.Дистанция); })
        .on('mouseover', tip.show)
        .on('mouseout', tip.hide)


    function type(d) {
        d.Дистанция = +d.Дистанция;
        return d;
    }
</script>

awesomeapp/statistics/templates/statistics/menu.html
{% extends "index.html" %}

{% block content %}
    <div class="row align-items-center menu_content">
        <div class="col-sm"></div>
        <div class="col-sm-6">

            <form action="{{ url_for('statistics.view', equipment_id=equipment_by_id.id) }}" method='post' novalidate>
                {{ form.hidden_tag() }}
                <div class="form-row">
                    <p class="h6">Выберите промежуток времени для общей статистики или дату для детальной статистики по заданному дню
                    <div class="form-group col-md-6">
                         <span class="sr-only">{{ form.start_date.label }}</span>
                        {{ form.start_date }}</p>
                        {% for error in form.start_date.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group col-md-6">
                         <span class="sr-only">{{ form.end_date.label }}</span>
                        {{ form.end_date }}</p>
                        {% for error in form.end_date.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <p>{{ form.submit }}</p>
            </form>

        </div>
        <div class="col-sm"></div>
    </div>
    <div class="row align-items-center menu_button">
        <div class="col-sm"></div>
        <div class="col-sm-3">
            <a 
                href="{{ url_for('statistics.add', equipment_id=equipment_by_id.id) }}"
                class="btn btn-lg btn-primary btn-block"
                role="button">
                    Добавить статистику
            </a>
        </div>
        <div class="col-sm-3">
            <a 
                href="{{ url_for('statistics.delete_equipment', equipment_id=equipment_by_id.id) }}" 
                onclick="return confirm('Вы уверены?')" 
                class="btn btn-lg btn-primary btn-block" 
                role="button">
                    Удалить инвентарь
            </a>
        </div>
        <div class="col-sm"></div>
    </div>

{% endblock %}

awesomeapp/statistics/templates/statistics/stats.html
{% extends "index.html" %}
{% block content %}
    <div class="row align-items-center statistics_content">
        <form class="form-signin" action="" method="post" novalidate enctype="multipart/form-data">
            <div class ='container'>
                {{ form.hidden_tag() }}
                <p class="h5 font-weight-normal">{{ title }}</p>       
                {% for name, group_field in fields.items() %}       
                    {{ name }}
                    <div class="form-row">
                    {% for field in group_field %}
                        <span class="sr-only">{{ field.label }}</span>
                        
                        <div class="col">{{ field }}</div>
                        
                        {% for error in field.errors  %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}
                    {% endfor %}
                    </div>
                {% endfor %}

                {{ form.story.label }}
                {{ form.story }}

                {{ form.photo.label }}
                {{ form.photo }}

                {{ form.submit }}
            </div>
        </form>
    </div>
{% endblock %}

awesomeapp/statistics/templates/statistics/stats_view.html
{% extends "index.html" %}

{% block content %}

<div class="row align-items-center stats_view_date">
    <div class="col-sm">
        {% if start_date  == end_date %}
            <p class="text-center h5 font-weight-normal">{{ start_date  }}
        {% else %}
            <p class="text-center h5 font-weight-normal">C {{ start_date  }} по {{ end_date }}:
        {% endif %}
    </div>
</div>
<div class="row align-items-center stats_view_content">
    <div class="col-sm-9" >
        {% if start_date  == end_date %}
            {% include('/statistics/carousel.html') %}
        {% else %}
            <div id="my_histogram"></div>
        {% endif %}
    </div>
    <div class="col-sm-3">
        <p class="small_text">Результаты:
        <div class="stats_text">
            {% for label, value in statistics.items() %}
                {% if value != 0 %}
                <p class="stats_text">{{ label }}: {{ value }}</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="row align-items-center stats_view_story">
    {% if start_date == end_date %}
        <div class="col-sm-9">
            {% if story_and_images.story is not none %}
                <p class="small_text">О тренировке:
                <p>{{ story_and_images.story }}
            {% endif %}
        </div>
        <div class="col-sm-3">
            <a 
                href="{{ url_for('statistics.delete_statistics', statistics_id=story_and_images.id, equipment_id=equipment_by_id.id) }}" 
                onclick="return confirm('Вы уверены?')" 
                class="btn btn-primary" 
                role="button">
                    Удалить статистику
            </a>
        </div>
    {% endif %}
</div>

{% include('/statistics/histogram.html') %}

{% endblock %}